### ISSUE TITLE
BIC format error after t=5 mast runs

### ISSUE THREAD

**Issue by fredjaya** [fredjaya/rec-mast#17]
On `concat.fa` and `set2_paragone` data. Might be slurm/scheduling issue
```
multiprocessing.pool.RemoteTraceback:                                                          
"""                                                                                            
Traceback (most recent call last):                                                             
  File "/home/u1070770/.conda/envs/rec-mast/lib/python3.10/multiprocessing/pool.py", line 125, 
in worker                                                                                      
    result = (True, func(*args, **kwds))                                                       
  File "/home/u1070770/.conda/envs/rec-mast/lib/python3.10/multiprocessing/pool.py", line 51, i
n starmapstar          
    return list(itertools.starmap(args[0], args[1]))                                           
  File "/home/u1070770/rec-mast/run.py", line 133, in mast                                     
    bic=get_bic(iqtree_out_path)               
  File "/home/u1070770/rec-mast/run.py", line 48, in get_bic                                   
    return(float(bic))                         
ValueError: could not convert string to float: ''                                              
"""                                            
                                              
```

**Comment by fredjaya** [comment]
Reverting back to nextflow instead of `multiprocessing,Pool()`
